### ISSUE TITLE
Add RDF file extension to the white list

### ISSUE THREAD

**Issue by cabral** [datopian/ckanext-noanonaccess#2]
Using `noanonaccess` along with DCAT extension will prevent the datasets to show at Google Data Search Engine and others. 

## Acceptance Criteria

* [ ] Being able to access a RDF file even when logged out of CKAN. Which allow Google crawlers to find the datasets

## Tasks

* [ ] Add `*.rdf` to the whitelist

## Analysis

`noanonaccess` already have a whitelist structure. 
https://github.com/datopian/ckanext-noanonaccess/blob/master/ckanext/noanonaccess/plugin.py#L20

We need to create a path that can receive any dataset that ends with extension `.rdf`

**Comment by anuveyatsu** [comment]
@cabral I'm not sure if this is correct - google crawlers should use frontend to index not the backend.

**Comment by cabral** [comment]
@anuveyatsu We are using proxy to send the content to the frontend. But still, the `.rdf` are unreachable due the `noanonaccess`

**Comment by anuveyatsu** [comment]
@cabral could you give me an example? I need to understand path structure.

**Comment by cabral** [comment]
@anuveyatsu If we follow the code structure, will be something like:
```
elif '.rdf' in environ['PATH_INFO']:
    return self.app(environ,start_response)
```

Because Python will check the `.rdf` against the whole `PATH_INFO`

**Comment by anuveyatsu** [comment]
Hey @cabral and maybe @gavram could you give me an example URL (from any host), not the code of how to do this? I'm asking because I'm not sure what is the problem here and we want to fix it for general purpose not just `rdf`.

**Comment by gavram** [comment]
@anuveyatsu Here are the links:
[Issue #105](https://gitlab.com/datopian/clients/ckan-montreal/-/issues/105)
http://donnees.montreal.ca/dataset/promenade-fleuve-montagne.rdf
https://montreal.l3.ckan.io/dataset/promenade-fleuve-montagne.rdf 

Maybe the solution can be extended to be configurable in `.ENV` with exceptions for `noannonaccess` (not to put exceptions in `noannonaccess` code directly, but to read them from `.ENV` file)

**Comment by anuveyatsu** [comment]
@gavram ok got it thanks! Would you mind to open a PR?

**Comment by gavram** [comment]
@anuveyatsu I will

**Comment by gavram** [comment]
@anuveyatsu @cabral 

FIXED. PR created [here](https://github.com/datopian/ckanext-noanonaccess/pull/3)
