### ISSUE TITLE
Did you mean to disable css and scripts?

### ISSUE THREAD

**Issue by benjaminschwetz** [datopian/ckanext-noanonaccess#6]
Hey,

not sure if this is an issue or was indeed your intention but right now the plugin also redirects to the login page for webassets (css, scripts).

I fixed it by adding 

```
elif environ['PATH_INFO'].startswith('/webassets/'):
            return self.app(environ,start_response)
```

**Comment by anuveyatsu** [comment]
@benjaminschwetz thanks for this. Would you mind to create a PR?

**Comment by anuveyatsu** [comment]
this might resolve this issue now: https://github.com/datopian/ckanext-noanonaccess/blob/fa7a59b0cc8fba44dbf52d83d3fb98fe095efd1f/ckanext/noanonaccess/plugin.py#L20-L21C44

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/datopian/ckanext-noanonaccess/pull/9/files#diff-e3beb1cb389808ed6a20892705cba6588fcfd161da811bab424d8aa0e0052204R55
